# Generated by Django 5.2.7 on 2025-11-01 17:14

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_num', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to=users.models.upload_image_path)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
