# Generated by Django 5.2.7 on 2025-11-01 17:14

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('Author', models.CharField(max_length=150, null=True)),
                ('publisher', models.CharField(max_length=150, null=True)),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('edition', models.CharField(blank=True, max_length=150, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=books.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(blank=True, to='categories.bookcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
